-- Trust Platform PostgreSQL baseline types.
-- UUID generation should be provided by the application or a vetted UUIDv7 extension.

CREATE TYPE platform.record_status AS ENUM ('ACTIVE','INACTIVE','SUSPENDED','CLOSED');

CREATE TYPE consent.consent_status AS ENUM ('ACTIVE','EXPIRED','REVOKED','SUSPENDED','SUPERSEDED');
CREATE TYPE application.application_status AS ENUM (
  'DRAFT','SUBMITTED','PROCESSING','INFORMATION_REQUIRED','MANUAL_REVIEW',
  'DECLINED','APPROVED','OFFERED','ACCEPTED','DISBURSEMENT_PENDING','DISBURSED','CANCELLED'
);
CREATE TYPE lending.loan_status AS ENUM (
  'DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','OFFERED','ACCEPTED',
  'DISBURSEMENT_PENDING','ACTIVE','PAST_DUE','DEFAULT','RESTRUCTURED','SETTLED','CANCELLED'
);
CREATE TYPE payments.payment_status AS ENUM (
  'INITIATED','PENDING','PROCESSING','SUCCEEDED','FAILED','UNKNOWN','REVERSED','CANCELLED'
);
CREATE TYPE payments.payment_direction AS ENUM ('INBOUND','OUTBOUND');
CREATE TYPE ledger.entry_type AS ENUM ('POSTING','REVERSAL','CORRECTION','ADJUSTMENT');
CREATE TYPE fraud.action_type AS ENUM (
  'ALLOW','STEP_UP','MONITOR','HOLD','MANUAL_REVIEW','LIMIT','RESTRICT','BLOCK','LOCK','CASE','INCIDENT'
);
CREATE TYPE collections.case_status AS ENUM (
  'CURRENT','DUE_SOON','DUE_TODAY','PAST_DUE','DELINQUENT','DEFAULT','RECOVERY','SETTLED'
);
CREATE TYPE collections.promise_status AS ENUM ('ACTIVE','FULFILLED','BROKEN','CANCELLED','SUPERSEDED');
CREATE TYPE identity.verification_status AS ENUM ('PENDING','PASSED','FAILED','MANUAL_REVIEW','EXPIRED');
CREATE TYPE models.lifecycle_status AS ENUM (
  'IDEA','DEVELOPMENT','VALIDATION','MODEL_RISK_REVIEW','APPROVED','CANARY','PRODUCTION','REVIEW','RETIRED'
);
CREATE TYPE reconciliation.recon_status AS ENUM ('OPEN','IN_PROGRESS','MATCHED','EXCEPTION','RESOLVED','CLOSED');
CREATE TYPE audit.actor_type AS ENUM ('CUSTOMER','EMPLOYEE','PARTNER','SYSTEM','VENDOR');
